name: Update View Count Badge

on:
  schedule:
    - cron: "0 * * * *"  # runs every hour
  workflow_dispatch: 

jobs:
  update-views:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Fetch View Count
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VIEW_COUNT=$(curl -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/traffic/views | jq '.count')
          sed -i "s|<!-- views -->|$VIEW_COUNT|g" README.md

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update view count in README"
          git push
        continue-on-error: true 
